language: node_js
node_js:
  - 5.0.0
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "Y9KkdeV3NQd2Vw1w8LZVsW5qxEtJ+kd2OMJqXKrmImECZC71bnikox2P20rsjI482p7XP6zsvkE1Y/RZ97KfwOoRNmC0imUvgRz4TXzlPOOjeRwnwdQnHlUJ8Kt5d+gvCPZ4m8WVMI8wJJ2tQgiFdttPN+H/QW8N66zVRtArSR55mwWIxFsGm2e37bKXmOTsLeOOaQxqwQTEcH4MbwBt2GLGVKHlBzBAhz9sT9TfB+jMMiDZ5E5XfQqyPqMkCnhaGAuhOMbf9pzVvQyv4zaYQFjzTHtM+YGsGOL7cmAb0C9o0BI1Uwh72SZEQqyKlhRmbAIxLFNvzbEIXWUaV2qXu1ljtTkFStTTafUdGCu2bPpW9yKhHUPitFy9a39CETdpLdThTLCiiuk5Eu+vdKY4EdQ+agZ8UdzS1N1f7U+zF6E89iHOanNwtsCeLQjcKELW/+3AvXz/swsuFrxBIrzH7L98ANFT/LLG+YepGSy4OV1N2w9emg7qH+pQC4OKUT0sBUYVkwFyvnc63YSy6NUwHWUcRcIdSm2GyFkbCriW8xD5EJOEnrfm7u5FdaDVXTppih3fSsKc/oZk4UIVHGqKqgtYJRovACZHdeaij1uWIyulxdJ4Ixk3sKC/yfFxNpqqnxM5chgHsSyptRZD4Qe3MIBnfeSC5v6+bDyaSQbNZ5A="